mutation SceneUpdate($input: SceneUpdateInput!) {
      sceneUpdate(input: $input) {
        ...SceneData
    __typename
    }
}

fragment SceneData on Scene {
  id
  details
  tags {
    id
    name
  }
  __typename
}